use db_rezervacija;

INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 1, 0, 0,  '2018-01-01' , 1, 1, 1, 'Arena',  'Film1' ,  'sala 1' );
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 2, 0, 0,  '2018-01-02' , 1, 1, 1, 'Arena', 'Film1','sala 1' );
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 3, 0, 0,  '2018-01-01' , 1 ,  1 ,  1 , 'Arena' ,  'Film1' ,  'sala 1' );
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 4, 0, 0,  '2018-01-02' , 1 ,  1 ,  1 ,  'Arena' ,  'Film1' ,  'sala 1' );
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 5, 0, 0,  '2018-01-03' , 2 ,  1 ,  2 ,  'Big' ,  'Film1'  ,  'sala 2' );
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 6, 0, 0,  '2018-01-03' , 3 ,  1 ,  3 ,  'Cineplexx' ,  'Film1' , 'sala 3' );
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija , broj_otkazanih_rezervacija  ,  datum_projekcije , id_bioskopa  ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 7, 0, 0, '2018-04-01', 1, 1, 1, 'Arena', 'Film1', 'sala 1');
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 8, 0, 0, '2018-04-01', 3, 1, 3, 'Cineplexx', 'Film1', 'sala 3');
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 9, 0, 0, '2018-04-01', 3, 2, 3, 'Cineplexx', 'Film2', 'sala 3');
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 10, 0, 0, '2018-01-01', 2, 1, 2, 'Big', 'Film1', 'sala 2');
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 11, 0, 0, '2018-02-01', 2, 3, 2, 'Big', 'Film3 ', 'sala 2');
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 12, 0, 0, '2018-03-01', 3, 2, 3, 'Cineplexx', 'Film2', 'sala 3');
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 13, 0, 0, '2018-04-01', 3, 3, 3, 'Cineplexx', 'Film3', 'sala 3');
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 14, 0, 0, '2018-01-01', 2, 3, 2, 'Big', 'Film3', 'sala 2');
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 15, 0, 0, '2018-02-01', 2, 2, 2, 'Big', 'Film2 ', 'sala 2');
INSERT INTO projekcija  ( projekcija_id ,  broj_aktivnih_rezervacija ,  broj_otkazanih_rezervacija ,  datum_projekcije ,  id_bioskopa ,  id_filma ,  id_sale ,  naziv_bioskopa ,  naziv_filma ,  oznaka_sale ) VALUES ( 16, 0, 0, '2018-03-01', 3, 2, 3, 'Cineplexx', 'Film2', 'sala 3');

INSERT INTO rezervacija  ( rezervacija_id ,  broj_reda_sedista ,  broj_sedista ,  datum_isteka_rezervacije ,  datum_rezervacije ,  id_korisnika ,  tip ,  projekcija_id ) VALUES ( 1 ,  1 ,  2 ,  '2018-10-10' ,  '2017-12-12' ,  1 ,  'AKTIVNA' ,  1 );
INSERT INTO rezervacija  ( rezervacija_id ,  broj_reda_sedista ,  broj_sedista ,  datum_isteka_rezervacije ,  datum_rezervacije ,  id_korisnika ,  tip ,  projekcija_id ) VALUES ( 2 ,  2 ,  3 ,  '2018-10-10' ,  '2017-12-11' ,  2 ,  'AKTIVNA' ,  2 );
INSERT INTO rezervacija  ( rezervacija_id ,  broj_reda_sedista ,  broj_sedista ,  datum_isteka_rezervacije ,  datum_rezervacije ,  id_korisnika ,  tip ,  projekcija_id ) VALUES ( 3 ,  4 ,  1 ,  '2018-10-10' ,  '2017-12-12' ,  4 ,  'AKTIVNA' ,  3 );
INSERT INTO rezervacija  ( rezervacija_id ,  broj_reda_sedista ,  broj_sedista ,  datum_isteka_rezervacije ,  datum_rezervacije ,  id_korisnika ,  tip ,  projekcija_id ) VALUES ( 4 ,  1 ,  1 ,  '2018-10-10' ,  '2017-12-11' ,  5 ,  'AKTIVNA' ,  4 );
INSERT INTO rezervacija  ( rezervacija_id ,  broj_reda_sedista ,  broj_sedista ,  datum_isteka_rezervacije ,  datum_rezervacije ,  id_korisnika ,  tip ,  projekcija_id ) VALUES ( 5 ,  2 ,  6 ,  '2018-10-10' ,  '2017-12-15' ,  6 ,  'AKTIVNA' ,  5 );
INSERT INTO rezervacija  ( rezervacija_id ,  broj_reda_sedista ,  broj_sedista ,  datum_isteka_rezervacije ,  datum_rezervacije ,  id_korisnika ,  tip ,  projekcija_id ) VALUES ( 6 ,  7 ,  2 ,  '2018-10-10' ,  '2017-12-18' ,  1 ,  'AKTIVNA' ,  6 );
INSERT INTO rezervacija  ( rezervacija_id ,  broj_reda_sedista ,  broj_sedista ,  datum_isteka_rezervacije ,  datum_rezervacije ,  id_korisnika ,  tip ,  projekcija_id ) VALUES ( 7 ,  7 ,  1 ,  '2018-10-10' ,  '2017-12-11' ,  2 ,  'AKTIVNA' ,  6 );
INSERT INTO rezervacija  ( rezervacija_id ,  broj_reda_sedista ,  broj_sedista ,  datum_isteka_rezervacije ,  datum_rezervacije ,  id_korisnika ,  tip ,  projekcija_id ) VALUES ( 8 ,  1 ,  2 ,  '2018-10-10' ,  '2017-12-10' ,  4 ,  'AKTIVNA' ,  1 );
INSERT INTO rezervacija  ( rezervacija_id ,  broj_reda_sedista ,  broj_sedista ,  datum_isteka_rezervacije ,  datum_rezervacije ,  id_korisnika ,  tip ,  projekcija_id ) VALUES ( 9 ,  2 ,  1 ,  '2018-10-10' ,  '2017-12-19' ,  5 ,  'OTKAZANA' ,  2 );
INSERT INTO rezervacija  ( rezervacija_id ,  broj_reda_sedista ,  broj_sedista ,  datum_isteka_rezervacije ,  datum_rezervacije ,  id_korisnika ,  tip ,  projekcija_id ) VALUES ( 10 ,  5 ,  5 ,  '2018-10-10' ,  '2017-12-22' ,  6 ,  'AKTIVNA' ,  3 );
INSERT INTO rezervacija  ( rezervacija_id ,  broj_reda_sedista ,  broj_sedista ,  datum_isteka_rezervacije ,  datum_rezervacije ,  id_korisnika ,  tip ,  projekcija_id ) VALUES ( 11 ,  3 ,  2 ,  '2018-10-10' ,  '2017-12-25' ,  1 ,  'OTKAZANA' ,  4 );


